name: Update Table

on: [push]
  # schedule:
  #   - cron: '0 7 * * MON'

jobs:
  update-table:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -U pipenv
        pipenv install
        pipenv install --dev

    - name: Run script
      run: pipenv run python repotrack/repotrack.py --gat ${{ secrets.ACCESS_TOKEN }} --no-empties | tee README.md

    - name: Check for changes
      run: |
        echo "nochanges=$(git diff --quiet)" >> $GITHUB_ENV
        echo ${{ env.nochanges }}

    - name: Create pull request
      if: ${{ env.nochanges == 1 }}
      uses: peter-evans/create-pull-request@v3
      with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: Automated table update
          title: Update table
          body: |
            A change has been detected, the table has been updated

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-table